learning_users/basic_app/urls.py
from django.conf.urls import url
from django.urls import path
from basic_app import views

# template tagging
app_name = 'basic_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.registration, name='registration'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basic_app.urls')),
    path('', views.index, name = 'index'),
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional classes
    
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank = True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm

# authentications
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout

# ==============================================================================
# ******************************************************************************

# Create your views here.
def index(req):
    return render(req, 'basic_app/index.html')

# ==============================================================================

@login_required
def special(req):
    return HttpResponse('special page!!')

# ==============================================================================

@login_required
def user_logout(req):
    logout(req)
    return HttpResponseRedirect(reverse('index'))

# ==============================================================================

def registration(req):

    registered = False

    if req.method == 'POST':
        user_form = UserForm(data = req.POST)
        profile_form = UserProfileInfoForm(data = req.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user

            if 'profile_pic' in req.FILES:
                profile.profile_pic = req.FILES['profile_pic']

            profile.save()

            registered=True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(req, 'basic_app/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

# =========================================================================================================================================

def user_login(req):

    if req.method == 'POST':
        username = req.POST.get('username')
        password = req.POST.get('password')

        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                login(req,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('ACCOUNT NOT ACTIVE!!')
        else:
            print('someone tried to login and failed!!')
            print('Username: {} and Password: {}'.format(username,password))
            return HttpResponse("Ivalid login details!!")
    else:
        return render(req, 'basic_app/login.html')

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'basic_app:index' %}">home</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:registration' %}">Register</a></li>



          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'basic_app:logout' %}">Logout</a></li>
            <li><a class="navbar-link" href="{% url 'basic_app:special' %}">Special</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>


  </body>
</html>

learning_users/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Home Page</h1>
</div>

{% endblock %}

learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>LOG IN</h1>
  <form class="" action="{% url 'basic_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Your Username">

    <label for="password">Password:</label>
    <input type="password" name="password" placeholder="Password">

    <input type="submit"  value ="Login">
  </form>
</div>

{% endblock %}

learning_users/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load static %}
{% block body_block %}

<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for registering!!</h1>
  {% else %}
    <h1>Register here </h1>

    <form class="" action="" method="POST" enctype="multipart/form-data">

      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input class="btn btn-primary" type="submit" name="" value="Register">

    </form>

  {% endif %}

</div>

{% endblock %}